# Generated by Django 2.1.1 on 2018-09-12 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Message'),
        ),
    ]
