# Generated by Django 2.1.1 on 2018-09-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20180912_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(blank=True, to='rooms.Message'),
        ),
    ]
