# Generated by Django 2.1.1 on 2018-09-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='event',
        ),
    ]
