# Generated by Django 2.1.1 on 2018-09-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20180916_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(blank=True, to='rooms.Message'),
        ),
    ]
