# Generated by Django 2.1.1 on 2018-09-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('date_matcher', '0002_auto_20180914_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
