# Generated by Django 2.1.1 on 2018-09-18 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_matcher', '0011_auto_20180918_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='max_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 19, 2, 35, 420577), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 19, 2, 35, 420577), null=True),
        ),
    ]
