# Generated by Django 2.1.1 on 2018-09-18 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_matcher', '0014_auto_20180918_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 1, 33, 53, 524030), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 1, 33, 53, 524030), null=True),
        ),
    ]
