# Generated by Django 2.1.1 on 2018-09-18 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_matcher', '0015_auto_20180919_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 1, 34, 34, 254360), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 1, 34, 34, 254360), null=True),
        ),
    ]
