# Generated by Django 2.1.5 on 2019-01-16 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_matcher', '0016_auto_20180919_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 5, 13, 18, 30374), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 5, 13, 18, 30374), null=True),
        ),
    ]
